import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Alec.Tunbridge' at '31/03/16 16:08' with Gradle 1.10
 *
 * @author Alec.Tunbridge, @date 31/03/16 16:08
 */
public class WordChainsTest {
    private WordChains wordChains;


    @Test
    public void distance_sameWords_zero() {
        assertThat(WordChains.distance("dog", "dog")).isEqualTo(0);
    }

    @Test
    public void distance_singleDifferingLetter_one() {
        assertThat(WordChains.distance("dog", "dob")).isEqualTo(1);
    }

    @Test
    public void distance_twoDifferingLetters_two() {
        assertThat(WordChains.distance("dog", "dgo")).isEqualTo(2);
    }
}
